# Generated by Django 3.1.4 on 2021-05-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210509_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='quary',
            new_name='query',
        ),
    ]
