# Generated by Django 3.1.4 on 2021-05-17 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210517_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('class_description', models.TextField(max_length=500)),
                ('class_images', models.ImageField(upload_to='myclasses')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='createdtimestamp')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_description', models.TextField(max_length=500)),
                ('subject_image', models.ImageField(upload_to='myfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='subjects1',
            name='class_name',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Subjects1',
        ),
        migrations.AddField(
            model_name='method',
            name='class_subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.subjects'),
        ),
    ]
