# Generated by Django 3.1.4 on 2021-05-17 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20210517_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Method',
            new_name='Classes',
        ),
    ]
