# Generated by Django 3.1.4 on 2021-05-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210520_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='myfile')),
                ('photo_description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_heading', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='myfile')),
                ('pdf_description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_heading', models.CharField(max_length=30)),
                ('caption', models.TextField(max_length=400)),
                ('video', models.FileField(upload_to='myfile')),
            ],
        ),
        migrations.CreateModel(
            name='Mergeall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.ManyToManyField(to='project.Notes')),
                ('pdf', models.ManyToManyField(to='project.Pdf')),
                ('vids', models.ManyToManyField(to='project.Video')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='notes',
            field=models.ManyToManyField(to='project.Mergeall'),
        ),
    ]
