# Generated by Django 3.1.4 on 2021-05-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20210523_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mergeall',
            old_name='notes',
            new_name='notes12',
        ),
    ]
