# Generated by Django 3.1.4 on 2021-05-23 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210523_2201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mergeall',
        ),
    ]
