# Generated by Django 3.1.4 on 2021-05-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_delete_mergeall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapters',
            old_name='pdf',
            new_name='pdf12',
        ),
    ]
