# Generated by Django 3.1.4 on 2021-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mail',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
