# Generated by Django 3.1.4 on 2021-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_course_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='paying',
            field=models.ManyToManyField(default=0, to='project.Course'),
        ),
    ]
