# Generated by Django 3.1.4 on 2021-07-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_faqs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqs',
            name='question',
            field=models.TextField(max_length=400),
        ),
    ]
