# Generated by Django 3.0.7 on 2021-07-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20210721_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='myfile')),
                ('description', models.TextField(max_length=400)),
                ('pdf', models.FileField(upload_to='myfile')),
                ('video', models.FileField(upload_to='myfile')),
            ],
        ),
    ]
