# Generated by Django 3.0.7 on 2021-07-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_subj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=400)),
                ('notes_pages', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='chapter',
        ),
        migrations.AddField(
            model_name='subjects',
            name='chapter',
            field=models.ManyToManyField(to='project.Chapters'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='paying',
            field=models.ManyToManyField(default='r', to='project.Course'),
        ),
    ]
